/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LinksIndexRouteImport } from './routes/links.index'
import { Route as LinksIdRouteImport } from './routes/links.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIndexRoute = LinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIdRoute = LinksIdRouteImport.update({
  id: '/links/$id',
  path: '/links/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/links/$id': typeof LinksIdRoute
  '/links/': typeof LinksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/links/$id': typeof LinksIdRoute
  '/links': typeof LinksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/links/$id': typeof LinksIdRoute
  '/links/': typeof LinksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analytics' | '/login' | '/register' | '/links/$id' | '/links/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analytics' | '/login' | '/register' | '/links/$id' | '/links'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/login'
    | '/register'
    | '/links/$id'
    | '/links/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  LinksIdRoute: typeof LinksIdRoute
  LinksIndexRoute: typeof LinksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/': {
      id: '/links/'
      path: '/links'
      fullPath: '/links/'
      preLoaderRoute: typeof LinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/$id': {
      id: '/links/$id'
      path: '/links/$id'
      fullPath: '/links/$id'
      preLoaderRoute: typeof LinksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  LinksIdRoute: LinksIdRoute,
  LinksIndexRoute: LinksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
